In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [6]:
import numpy as np

In [3]:
n = np.array((1,2,3))
print(n)

[1 2 3]


# Numpy Arrays

In [4]:
my_list = [1,2,3]

In [5]:
import numpy as np

Casting list to array in the below step

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

Getting 2d arrays:

In [9]:
my_mat = ([1,2,3],[4,5,6],[7,8,9])

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# -----------------------------

In [19]:
np.arange(0)

array([], dtype=int32)

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [23]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [24]:
1d_array = np.arange(-1,10,0.5)

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,
        4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [26]:
# Arrays from Lists:

In [27]:
from_list = np.array([1,2,3])

In [28]:
from_list

array([1, 2, 3])

In [30]:
#Consuming less memory

In [31]:
from_list = np.array([1,2,3],dtype = np.int8)

In [32]:
print(type(from_list[0]))

<class 'numpy.int8'>


In [33]:
#2d Arrays

In [35]:
from_list = np.array([[1,2,3],[4,5,6]],dtype = np.int8)

In [36]:
from_list

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [37]:
array_2d = np.array((np.arange(0,8,2),np.arange(1,9,2)),dtype = np.int8)

In [39]:
array_2d

array([[0, 2, 4, 6],
       [1, 3, 5, 7]], dtype=int8)

In [40]:
# We can also verify 2d array by printing its shape.Shape returns the number of cols and rows in 2d array and only columns in
#1d array

In [41]:
print(array_2d.shape)

(2, 4)


In [44]:
#To change the shape we can use reshape method

In [45]:
print(array_2d.reshape(4,2))

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [47]:
# In reshape,3d is also possible
print(array_2d.reshape(8))

[0 2 4 6 1 3 5 7]


In [49]:
# Empty Arrays
# 3 methods are available

In [50]:
empty_array = np.zeros((2,2))

In [51]:
print(empty_array)

[[0. 0.]
 [0. 0.]]


In [52]:
empty_array = np.ones((2,2))

In [53]:
print(empty_array)

[[1. 1.]
 [1. 1.]]


empty() produces random numbers

In [54]:
empty_array = np.empty((2,2))

In [55]:
empty_array

array([[1., 1.],
       [1., 1.]])

In [56]:
empty_array = np.empty((2,2,2))

In [57]:
empty_array

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 6.66000491e-321],
        [1.78019082e-306, 8.90111707e-307]]])

In [59]:
# eye()

In [60]:
eye_array = np.eye(3)

In [61]:
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
eye_array = np.eye(3,k = -1)

In [69]:
eye_array

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [64]:
eye_array = np.eye(3,k = 1)

In [65]:
eye_array

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [70]:
# Manipulating values of array

In [74]:
# Here replacing values of eye_array with 2 where it was previously zero
# The expression within bracket is the filter.
# The expression within bracket reads where eye_array value equal to zero

In [71]:
eye_array[eye_array == 0] = 2

In [72]:
eye_array

array([[2., 2., 2.],
       [1., 2., 2.],
       [2., 1., 2.]])

In [80]:
eye_array[eye_array < 2] = 9

In [81]:
eye_array

array([[2., 2., 2.],
       [9., 2., 2.],
       [2., 9., 2.]])

In [82]:
# Filtering rows

In [83]:
eye_array[0] = 5

In [84]:
eye_array

array([[5., 5., 5.],
       [9., 2., 2.],
       [2., 9., 2.]])

In [85]:
eye_array[:2] = 10

In [86]:
eye_array

array([[10., 10., 10.],
       [10., 10., 10.],
       [ 2.,  9.,  2.]])

In [87]:
# Filtering columns

In [88]:
eye_array[0:,0] = 7

In [89]:
eye_array

array([[ 7., 10., 10.],
       [ 7., 10., 10.],
       [ 7.,  9.,  2.]])

In [90]:
eye_array[0:,-1] = 9

In [91]:
eye_array

array([[ 7., 10.,  9.],
       [ 7., 10.,  9.],
       [ 7.,  9.,  9.]])

In [92]:
eye_array[2] = 12

In [93]:
eye_array

array([[ 7., 10.,  9.],
       [ 7., 10.,  9.],
       [12., 12., 12.]])

In [94]:
eye_array[0:2,1:] = 11

In [95]:
eye_array

array([[ 7., 11., 11.],
       [ 7., 11., 11.],
       [12., 12., 12.]])

In [96]:
# Sort Arrays by rows

In [114]:
unsorted_array = np.array((np.arange(4,1,-1),np.arange(8,5,-1)))
                          # array_2d = np.array((np.arange(0,8,2),np.arange(1,9,2)),dtype = np.int8)

In [116]:
sorted_array = np.sort(unsorted_array)

In [117]:
print(sorted_array)

[[2 3 4]
 [6 7 8]]


In [118]:
# Sorting arrays by columns

In [7]:
unsorted_array = np.array((np.arange(4,1,-1),np.arange(8,5,-1)))

In [8]:
sorted_array = np.sort(unsorted_array,axis = 0,kind = "mergesort")
# where 0 indicates columns and -1 which is the default indicates rows

In [9]:
sorted_array

array([[4, 3, 2],
       [8, 7, 6]])

In [1]:
# Copying arrays
# view() modifies original array as well

In [16]:
 # view() modifies original array as well.Only the original array value gets modified and not its shape
my_view = sorted_array.view()

In [11]:
my_copy = sorted_array.copy()

In [12]:
my_view[0:] = 4

In [13]:
my_view

array([[4, 4, 4],
       [4, 4, 4]])

In [14]:
sorted_array

array([[4, 4, 4],
       [4, 4, 4]])

In [17]:
 my_copy

array([[4, 3, 2],
       [8, 7, 6]])

In [18]:
sorted_array

array([[4, 4, 4],
       [4, 4, 4]])

In [19]:
# _____________________________________________________________________________________________________________________

In [29]:
a = np.zeros((3,3),dtype = np.int64)

In [30]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [31]:
a[0:] = 2

In [32]:
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [33]:
print(a.dtype)

int64


In [34]:
b = np.arange(1,10).reshape((3,3))

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
print(b.dtype)

int32


In [37]:
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [41]:
# fill()
# fill() applies the changes in place and hence there is no need of re assigning it to another variable

In [42]:
a.fill(8) 

In [43]:
a

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int64)

In [ ]:
# Alternatively fill() method's use can be obtained using assignment operator

In [44]:
a += 3

In [45]:
a

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]], dtype=int64)

In [46]:
a -= 3

In [47]:
a


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int64)

In [48]:
a *= 3

In [49]:
a

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]], dtype=int64)

In [51]:
a /= 3
# The error below occurs due to us commanding numpy to store only int.If we remove dtype then we can store float in the array


UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [52]:
# ARITHMETIC METHODS

In [53]:
array_sum = a.sum()

In [54]:
array_sum


216

In [58]:
# Getting the sum of each of the column.This is done by specifying axis = 0 inside the sum() 

In [56]:
array_sum = a.sum(axis = 0)

In [57]:
array_sum

array([72, 72, 72], dtype=int64)

In [ ]:
# Getting the sum of each of the row.This is done by specifying axis = 1 inside the sum() 

In [60]:
array_sum = a.sum(axis = 1)

In [61]:
array_sum

array([72, 72, 72], dtype=int64)

In [62]:
# prod()

In [63]:
array_prod = a.prod()

In [64]:
array_prod

2641807540224

In [65]:
# mean()

In [66]:
array_avg = a.mean()

In [67]:
array_avg

24.0

In [68]:
array_max,array_min = a.min(),a.max()

In [69]:
array_max

24

In [70]:
array_min

24

In [72]:
# Getting the index of min and max values instead of the actual values
# a.argmax(),a.minmax()

In [73]:
# ptp(): difference of max and min values

In [74]:
peak_to_peak = a.ptp()

In [75]:
peak_to_peak

0

In [76]:
# Flattening arrays,ie,instead of rows and columns arrange the data in a single line

In [77]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
b.size

9

In [79]:
array_flat = b.reshape(b.size)

In [80]:
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]], dtype=int64)

In [92]:
# flatten(): This makes a copy of the original array.Does not modify original array

In [83]:
array_flat = a.flatten()

In [84]:
array_flat

array([24, 24, 24, 24, 24, 24, 24, 24, 24], dtype=int64)

In [86]:
# ravel(): Creates a view of the original array.Modifies original array

In [87]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
array_flat = b.ravel()

In [89]:
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Modifies original array 

In [90]:
array_flat += 5

In [91]:
array_flat

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# repeat values/arrays